#!/usr/bin/env bash
# Idempotent repository bootstrap for the Helm dev environment.
# Installs system deps (MongoDB + python venv tooling), Python/JS packages,
# and generates local .env files when they are missing.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# 1. System dependencies: MongoDB server + python venv module.
#    The default base image ships Python 3.12, Node 22 and Yarn 1.x, but not
#    the venv module or a local MongoDB.
# ---------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive

if ! dpkg -s python3.12-venv >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3.12-venv
fi

if ! command -v mongod >/dev/null 2>&1; then
  sudo apt-get install -y -qq curl gnupg
  curl -fsSL https://pgp.mongodb.com/server-8.0.asc \
    | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor --yes
  . /etc/os-release
  echo "deb [ arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu ${UBUNTU_CODENAME}/mongodb-org/8.0 multiverse" \
    | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq mongodb-org
fi

# ---------------------------------------------------------------------------
# 2. Backend Python dependencies (isolated venv).
# ---------------------------------------------------------------------------
cd "$REPO_ROOT/backend"
python3 -m venv .venv
.venv/bin/pip install --upgrade pip >/dev/null
.venv/bin/pip install -r requirements.txt

# Local development .env (not committed). Uses the local MongoDB started by
# start.sh. Secrets are random per environment; real integrations require your
# own keys (see backend/.env.example).
if [ ! -f .env ]; then
  SESSION_SECRET="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))')"
  OAUTH_STATE_SECRET="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))')"
  cat > .env <<EOF
# Local development environment (auto-generated by .cursor/install.sh)
ENVIRONMENT=development
MONGO_URL=mongodb://localhost:27017
DB_NAME=helm
SESSION_SECRET=${SESSION_SECRET}
OAUTH_STATE_SECRET=${OAUTH_STATE_SECRET}
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
FRONTEND_URL=http://localhost:3000
APP_URL=http://localhost:3000
CORS_ORIGINS=http://localhost:3000
ALLOW_DEMO_LOGIN=false
DEMO_RESET_ENABLED=false
SETUP_SECRET=local-dev-setup-secret
EOF
fi

# ---------------------------------------------------------------------------
# 3. Frontend JS dependencies + local .env.
# ---------------------------------------------------------------------------
cd "$REPO_ROOT/frontend"
yarn install --frozen-lockfile

if [ ! -f .env ]; then
  cat > .env <<'EOF'
# Local development (auto-generated by .cursor/install.sh)
# Empty backend URL => same-origin /api proxied to http://localhost:8001 (see src/setupProxy.js)
REACT_APP_BACKEND_URL=
HOST=0.0.0.0
PORT=3000
BROWSER=none
WDS_SOCKET_PORT=0
EOF
fi

echo "Helm dev environment install complete."
